/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 earth.glb --shadows
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function RotatingEarth(props){
  const earthmesh = React.useRef();
  const { nodes, materials } = useGLTF('/earth.glb')
  useFrame(({clock})=>{
    const a = clock.getElapsedTime();
    earthmesh.current.rotation.y = a * 0.8;
  })

  return (
    <group {...props} dispose={null}>
      <mesh ref={earthmesh} castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={1.75} />
    </group>
  )
}

useGLTF.preload('/earth.glb')
