/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 jupiter.glb -T --shadows
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jupiter-d252c96ae3de48d7968b1206522ba9f5
Title: Jupiter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Jupiter(props) {
  const jupitermesh = React.useRef();

  useFrame(({clock})=>{
    const a = clock.getElapsedTime();
    jupitermesh.current.rotation.z = a * 0.5;
  })

  const { nodes, materials } = useGLTF('/jupiter-transformed.glb')
  
  return (
    <group {...props} dispose={null}>
      <mesh ref={jupitermesh} castShadow receiveShadow geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={2} />
    </group>
  )
}

useGLTF.preload('/jupiter-transformed.glb')
