/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mercury.glb -T --shadows
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercury-32347fa4ec1a4987b71f461a401d91c4
Title: Mercury
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Mercury(props) {
  const mercurymesh = React.useRef();

  useFrame(({clock})=>{
    const a = clock.getElapsedTime();
    mercurymesh.current.rotation.z = a * 1.8;
  })

  const { nodes, materials } = useGLTF('/mercury-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh ref={mercurymesh} castShadow receiveShadow geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={1.25} />
    </group>
  )
}

useGLTF.preload('/mercury-transformed.glb')
