/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 neptune.glb -T --shadows
Author: SunnyChen753/SW fan (https://sketchfab.com/sunnychen753)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neptune-bbc9710348434903a3e9771976adaa10
Title: Neptune
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/neptune-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Planeta_Planeta_0.geometry} material={materials.Planeta} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Atmosfera_Atmosfera_0.geometry} material={materials.Atmosfera} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/neptune-transformed.glb')
